import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { StoreProvider } from "@/store/provider";
import QuickViewModal from "@/components/product/QuickViewModal";
import SearchOverlay from "@/components/search/SearchOverlay";
import NavigationLoader from "@/components/layout/NavigationLoader";
import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col selection:bg-[#0A0A0A] selection:text-white" suppressHydrationWarning>
        <StoreProvider>
          {children}
          <NavigationLoader />
          <QuickViewModal />
          <SearchOverlay />
          <Toaster position="bottom-right" />
        </StoreProvider>
      </body>
    </html>
  );
}
